
create or replace view enet.unitrecipes_v as
    select RecipeGrpNum,
           RecipeNum,
           Version,
           RecipeName,
           RecipeDescription,
           RecipeComment,
           UnitRecipeNum,
           Unit,
           UnitRecipeComment,
           BatchID,
           ChargeNr,
           ProductName,
           ItemNr,
           OrderID,
           SerialNr,
           Started,
           Finished,
           RunNr,
           RunTotal,
           FinishType
    from efr_data.k1_apimpp_1_gb_unitrecipe
    union all
    select RecipeGrpNum,
           RecipeNum,
           Version,
           RecipeName,
           RecipeDescription,
           RecipeComment,
           UnitRecipeNum,
           Unit,
           UnitRecipeComment,
           BatchID,
           ChargeNr,
           ProductName,
           ItemNr,
           OrderID,
           SerialNr,
           Started,
           Finished,
           RunNr,
           RunTotal,
           FinishType
    from efr_data.k1_apimpp_2_gb_unitrecipe;
